"""Add job_satisfaction to User model

Revision ID: ad0b59533d02
Revises: 
Create Date: 2025-08-25 12:55:10.154899

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ad0b59533d02'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('members', sa.Column('job_satisfaction', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('members', 'job_satisfaction')
    # ### end Alembic commands ###